// <auto-generated />
using IlanProjesi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IlanProjesi.Migrations
{
    [DbContext(typeof(AllData))]
    partial class AllDataModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("IlanProjesi.Data.AllData+Araba", b =>
                {
                    b.Property<int>("ArabaId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ArabaAcıklama");

                    b.Property<string>("ArabaAdres");

                    b.Property<decimal>("ArabaFiyat");

                    b.Property<string>("ArabaModel");

                    b.Property<string>("ArabaResim");

                    b.HasKey("ArabaId");

                    b.ToTable("araba");
                });

            modelBuilder.Entity("IlanProjesi.Data.AllData+Is", b =>
                {
                    b.Property<int>("IsId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("IsAcıklama");

                    b.Property<string>("IsAdres");

                    b.HasKey("IsId");

                    b.ToTable("ıs");
                });

            modelBuilder.Entity("IlanProjesi.Data.AllData+Konut", b =>
                {
                    b.Property<int>("KonutId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("KonutAdres");

                    b.Property<string>("KonutAçıklama");

                    b.Property<decimal>("KonutFiyat");

                    b.Property<string>("KonutResim");

                    b.HasKey("KonutId");

                    b.ToTable("konut");
                });
#pragma warning restore 612, 618
        }
    }
}
